# Generated by Django 6.0.7 on 2026-08-24 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='last_delivered_seq',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='client_msg_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='rev_seq',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'rev_seq'], name='chat_message_conv_rev'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_msg_id', ''), _negated=True), fields=('conversation', 'client_msg_id'), name='chat_message_uniq_client_id'),
        ),
    ]
